name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Copy files to droplet (optional, if not using git pull)
        # uses: appleboy/scp-action@v0.1.7
        # with:
        #   host: ${{ secrets.DO_HOST }}
        #   username: root
        #   key: ${{ secrets.DO_SSH_KEY }}
        #   source: "."
        #   target: "/root/data-form"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /root/data-form/client
            git pull origin main
            docker build -t code-form .
            docker stop code-form || true
            docker rm code-form || true
            docker run -d --name code-form -p 80:80 code-form